services:
    hackzilla_ticket.listener:
        class: Hackzilla\Bundle\TicketBundle\EventListener\UserLoad
        arguments:
            - '%hackzilla_ticket.model.user.class%'
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    hackzilla_ticket.ticket_manager:
        class: Hackzilla\TicketMessage\Manager\TicketManager
        arguments:
            - '%hackzilla_ticket.model.ticket.class%'
            - '%hackzilla_ticket.model.message.class%'
        calls:
            - [ setStorageManager, ['@hackzilla_ticket.storage_manager'] ]
            - [ setEventManager, ['@hackzilla_ticket.event_manager'] ]
            - [ setUserManager, ['@hackzilla_ticket.user_manager'] ]
            - [ setTranslateManager, ['@hackzilla_ticket.translate_manager'] ]

    hackzilla_ticket.form.type.ticket:
        class: Hackzilla\Bundle\TicketBundle\Form\Type\TicketType
        arguments:
            - '%hackzilla_ticket.model.ticket.class%'
        tags:
            - { name: form.type, alias: hackzilla_ticket }

    hackzilla_ticket.form.type.ticket_message:
        class: Hackzilla\Bundle\TicketBundle\Form\Type\TicketMessageType
        arguments:
            - '@hackzilla_ticket.user_manager'
            - '@hackzilla_ticket.features'
            - '%hackzilla_ticket.model.message.class%'
        tags:
            - { name: form.type, alias: hackzilla_ticket_message }

    hackzilla_ticket.features:
        class: Hackzilla\Bundle\TicketBundle\Component\TicketFeatures
        arguments:
            - '%hackzilla_ticket.features%'
            - '%hackzilla_ticket.model.message.class%'

    hackzilla_ticket.component.twig_extension.ticket_features:
        class: Hackzilla\Bundle\TicketBundle\TwigExtension\TicketFeatureExtension
        arguments:
            - '@hackzilla_ticket.features'
        tags:
            - { name: twig.extension }

    hackzilla_ticket.component.twig_extension.ticket_global:
        class: Hackzilla\Bundle\TicketBundle\TwigExtension\TicketGlobalExtension
        arguments:
            - '%hackzilla_ticket.templates%'
        tags:
            - { name: twig.extension }

    hackzilla_ticket.file_upload_subscriber:
        class: Hackzilla\Bundle\TicketBundle\EventListener\FileSubscriber
        tags:
            - { name: kernel.event_subscriber }

### Event Managers

    hackzilla_ticket.event_manager.nothing:
        class: Hackzilla\Bundle\TicketBundle\Manager\EventManager\DoNothingEventManager

    hackzilla_ticket.event_manager.symfony:
        class: Hackzilla\Bundle\TicketBundle\Manager\EventManager\SymfonyEventManager
        arguments:
            - '@event_dispatcher'

### Storage Managers

    hackzilla_ticket.storage_manager.nothing:
        class: Hackzilla\Bundle\TicketBundle\Manager\StorageManager\DoNothingStorageManager

    hackzilla_ticket.storage_manager.doctrine_orm:
        class: Hackzilla\Bundle\TicketBundle\Manager\StorageManager\DoctrineOrmStorageManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@hackzilla_ticket.user_manager'
            - '%hackzilla_ticket.model.ticket.class%'
            - '%hackzilla_ticket.model.message.class%'

### User Managers

    hackzilla_ticket.user_manager.nothing:
        class: Hackzilla\Bundle\TicketBundle\Manager\UserManager\DoNothingUserManager

    hackzilla_ticket.user_manager.symfony:
        class: Hackzilla\Bundle\TicketBundle\Manager\UserManager\SymfonyUserManager
        arguments:
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '%hackzilla_ticket.admin_role%'

### Translate Managers

    hackzilla_ticket.translate_manager.nothing:
        class: Hackzilla\Bundle\TicketBundle\Manager\TranslateManager\DoNothingTranslateManager

    hackzilla_ticket.translate_manager.symfony:
        class: Hackzilla\Bundle\TicketBundle\Manager\TranslateManager\SymfonyTranslateManager
        arguments:
            - '@translator'
