services:
    hackzilla_ticket.listener:
        class: Hackzilla\Bundle\TicketBundle\EventListener\UserLoad
        arguments:
            - '%hackzilla_ticket.model.user.class%'
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    hackzilla_ticket.user_manager:
        class: Hackzilla\Bundle\TicketBundle\Manager\UserManager
        arguments:
            - '@security.token_storage'
            - '@hackzilla_ticket.user_repository'
            - '@security.authorization_checker'

    hackzilla_ticket.user_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - '%hackzilla_ticket.model.user.class%'

    hackzilla_ticket.ticket_manager:
        class: Hackzilla\Bundle\TicketBundle\Manager\TicketManager
        arguments:
            - '%hackzilla_ticket.model.ticket.class%'
            - '%hackzilla_ticket.model.message.class%'
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager'] ]
            - [ setTranslator, ['@translator'] ]

    hackzilla_ticket.form.type.ticket:
        class: Hackzilla\Bundle\TicketBundle\Form\Type\TicketType
        arguments:
            - '%hackzilla_ticket.model.ticket.class%'
        tags:
            - { name: form.type, alias: hackzilla_ticket }

    hackzilla_ticket.form.type.ticket_message:
        class: Hackzilla\Bundle\TicketBundle\Form\Type\TicketMessageType
        arguments:
            - '@hackzilla_ticket.user_manager'
            - '@hackzilla_ticket.features'
            - '%hackzilla_ticket.model.message.class%'
        tags:
            - { name: form.type, alias: hackzilla_ticket_message }

    hackzilla_ticket.features:
        class: Hackzilla\Bundle\TicketBundle\Component\TicketFeatures
        arguments:
            - '%hackzilla_ticket.features%'
            - '%hackzilla_ticket.model.message.class%'

    hackzilla_ticket.component.twig_extension.ticket_features:
        class: Hackzilla\Bundle\TicketBundle\TwigExtension\TicketFeatureExtension
        arguments:
            - '@hackzilla_ticket.features'
        tags:
            - { name: twig.extension }

    hackzilla_ticket.component.twig_extension.ticket_global:
        class: Hackzilla\Bundle\TicketBundle\TwigExtension\TicketGlobalExtension
        arguments:
            - '%hackzilla_ticket.templates%'
        tags:
            - { name: twig.extension }

    hackzilla_ticket.file_upload_subscriber:
        class: Hackzilla\Bundle\TicketBundle\EventListener\FileSubscriber
        tags:
            - { name: kernel.event_subscriber }
