language: php
warnings_are_errors: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: SYMFONY_VERSION="~2.8.0"
    - php: 5.6
      env: SYMFONY_VERSION="~3.0.0"
    - php: 5.6
      env: SYMFONY_VERSION="~3.1.0"
    - php: 5.6
      env: SYMFONY_VERSION="~3.2.0"
    - php: 5.6
      env: INSTALL_VICH_UPLOADER_BUNDLE=true
    - php: 7.2
      env: SYMFONY_VERSION="^4.1@dev"
  allow_failures:
    - php: nightly
    - php: hhvm
    - env: SYMFONY_VERSION="^4.1@dev"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - if [[ $TRAVIS_PHP_VERSION != hhvm && -f xdebug.ini ]]; then phpenv config-rm xdebug.ini; fi
  - if [ "$GITHUB_OAUTH_TOKEN" != "" ]; then echo -e $GITHUB_OAUTH_TOKEN && composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - if [ -n $INSTALL_VICH_UPLOADER_BUNDLE ]; then composer require "vich/uploader-bundle" --no-update; fi;
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - if [[ -n $INSTALL_VICH_UPLOADER_BUNDLE ]]; then make test_with_vichuploaderbundle; else make test; fi;
